<ul>
	<li>
		<a href="http://amiga.sourceforge.net/">Amiga.sf</a>:
		<a href="http://amiga.sourceforge.net/index.php?showpackage=ngIRCd">Port</a>
	</li>
	<li>
		<a href="http://www.archlinux.org/">Arch Linux</a>:
		<a href="http://aur.archlinux.org/packages.php?ID=11545">pkg</a>
	</li>
	<li>
		<a href="http://www.debian.org/">Debian Linux</a>:
		<a href="http://packages.debian.org/ngircd">deb</a>
	</li>
	<li>
		<a href="http://fedoraproject.org/">Fedora Linux</a>:
		<a href="https://admin.fedoraproject.org/pkgdb/packages/name/ngircd/">rpm</a>
	</li>
	<li>
		<a href="http://www.finkproject.org/">Fink Project</a>:
		<a href="http://pdb.finkproject.org/pdb/package.php/ngircd">Port</a>
	</li>
	<li>
		<a href="http://www.freebsd.org/">FreeBSD</a>:
		<a href="http://www.freebsd.org/cgi/ports.cgi?query=ngircd&amp;stype=all">Port</a>
	</li>
	<li>
		<a href="http://www.gentoo.org/">Gentoo Linux</a>:
		<a href="http://packages.gentoo.org/package/net-irc/ngircd">ebuild</a>
	</li>
	<li>
		<a href="http://www.macports.org/">Mac Ports</a>:
		<a href="http://trac.macports.org/browser/trunk/dports/irc/ngircd/Portfile">Port</a>
	<li>
		<a href="http://www.opensuse.org/">OpenSUSE</a>:
		<a href="http://download.opensuse.org/repositories/server:/irc/">rpm</a>
	</li>
	<li>
		<a href="http://www.ubuntu.com/">Ubuntu Linux</a>:
		<a href="http://packages.ubuntu.com/ngircd">deb</a>
	</li>
</ul>

