<h4>BSD</h4>
<ul>
	<li>
		<a href="https://www.freebsd.org/">FreeBSD</a>:
		<a href="https://ports.freebsd.org/cgi/ports.cgi?query=ngircd">Port</a>
	</li>
	<li>
		<a href="https://www.openbsd.org/">OpenBSD</a>:
		<a href="https://openports.pl/path/net/ngircd">Port</a>
	</li>
</ul>
<h4>Linux</h4>
<ul>
	<li>
		<a href="https://www.debian.org/">Debian Linux</a>:
		<a href="https://packages.debian.org/ngircd">deb</a>
	</li>
	<li>
		<a href="https://fedoraproject.org/">Fedora Linux</a>:
		<a href="https://packages.fedoraproject.org/pkgs/ngircd/ngircd/">rpm</a>
	</li>
	<li>
		<a href="https://www.gentoo.org/">Gentoo Linux</a>:
		<a href="https://packages.gentoo.org/package/net-irc/ngircd">ebuild</a>
	</li>
	<li>
		<a href="https://www.opensuse.org/">OpenSUSE</a>:
		<a href="https://software.opensuse.org/package/ngircd?search_term=ngircd">rpm</a>
	</li>
	<li>
		<a href="https://openwrt.org/">OpenWRT</a>:
		<a href="https://openwrt.org/packages/pkgdata/ngircd">Package</a>
	<li>
		<a href="https://www.ubuntu.com/">Ubuntu Linux</a>:
		<a href="https://packages.ubuntu.com/ngircd">deb</a>
	</li>
</ul>
<h4>macOS</h4>
<ul>
	<li>
		<a href="https://www.finkproject.org/">Fink Project</a>:
		<a href="https://pdb.finkproject.org/pdb/package.php/ngircd">Port</a> (<em class="outdated">outdated!</em>)
	</li>
	<li>
		<a href="https://brew.sh/">Homebrew</a>:
		<a href="https://formulae.brew.sh/formula/ngircd">Formula</a>
	</li>
	<li>
		<a href="https://www.macports.org/">Mac Ports</a>:
		<a href="https://trac.macports.org/browser/trunk/dports/irc/ngircd/Portfile">Port</a> (<em class="outdated">outdated!</em>)
	</li>
</ul>
