<ul>
	<li>
		<a href="http://www.debian.org/">Debian Linux</a>:
		<a href="http://debian.barton.de/debian/pool/main/n/ngircd/">deb</a>
		(Autor: Alex Barton)
		<small><ul>
			<li>
				<q>ngircd</q>: the <em>standard
				distribution</em>, including support for syslog
				logging and compressed server-links.
			</li>
			<li>
				<q>ngircd-full</q>: <q>standard</q> + TCP
				wrappers, IDENT requests, IPv6 and SSL.
			</li>
			<li>
				<q>ngircd-full-dbg</q>: <q>full</q> including
				debug code and debug symbols (<q>not
				stripped</q>).
			</li>
		</ul></small>
	</li>
</ul>
