<ul>
	<li><a href="doc/README.md">README.md</a></li>
	<li><a href="doc/INSTALL.md">INSTALL.md</a></li>
	<li><a href="doc/QuickStart.md">QuickStart.md</a></li>
</ul>
<ul>
	<li><a href="doc/sample-ngircd.conf">sample-ngircd.conf</a>
</ul>
<ul>
	<li><a href="doc/NEWS">NEWS</a>
	<li><a href="doc/ChangeLog">ChangeLog</a>
	<li><a href="doc/FAQ.md">FAQ.md</a>
</ul>
<ul>
	<li><a href="doc/AUTHORS">AUTHORS</a>
	<li><a href="doc/Bopm.txt">Bopm.txt</a>
	<li><a href="doc/Capabilities.txt">Capabilities.txt</a>
	<li><a href="doc/Commands.txt">Commands.txt</a>
	<li><a href="doc/Contributing.txt">Contributing.txt</a>
	<li><a href="doc/COPYING">COPYING</a>
	<li><a href="doc/HowToRelease.txt">HowToRelease.txt</a>
	<li><a href="doc/Modes.txt">Modes.txt</a>
	<li><a href="doc/PAM.txt">PAM.txt</a>
	<li><a href="doc/Platforms.txt">Platforms.txt</a>
	<li><a href="doc/Protocol.txt">Protocol.txt</a>
	<li><a href="doc/RFC.txt">RFC.txt</a>
	<li><a href="doc/Services.txt">Services.txt</a>
	<li><a href="doc/SSL.md">SSL.md</a>
</ul>
<ul>
	<li><a href="doc/README-AUX.txt">README-AUX.txt</a>
	<li><a href="doc/README-BeOS.txt">README-BeOS.txt</a> (deutsch)
	<li><a href="doc/README-Interix.txt">README-Interix.txt</a>
</ul>
