<dl>
	<dt>
		<strong>ngIRCd Release 18</strong> (2011-07-10):
	</dt>
	<dd>
		<p>Server: <em>ftp.berlios.de</em> (FTP)
		(<a href="ftp://ftp.berlios.de/pub/ngircd/">ftp</a>):
		<a href="ftp://ftp.berlios.de/pub/ngircd/ngircd-18.tar.gz">ngircd-18.tar.gz</a>
		<br>Server: <em>ngircd.barton.de</em> (HTTP)
		(<a href="http://ngircd.barton.de/pub/ngircd/">ftp</a>):
		<a href="http://ngircd.barton.de/pub/ngircd/ngircd-18.tar.gz">ngircd-18.tar.gz</a>
		</ul>
	</dd>
</dl>
