<dl>
	<dt>
		<strong>ngIRCd Release 22~rc1</strong> (2014-09-29):
	</dt>
	<dd>
		Server: <em>ngircd.barton.de</em>
		(<a href="http://ngircd.barton.de/pub/ngircd/">http</a>):
		<a href="http://ngircd.barton.de/pub/ngircd/ngircd-22~rc1.tar.gz">ngircd-22~rc1.tar.gz</a>
		(<a href="http://ngircd.barton.de/pub/ngircd/ngircd-22~rc1.tar.gz.sig">Sig</a>),
		<a href="http://ngircd.barton.de/pub/ngircd/ngircd-22~rc1.tar.xz">tar.xz</a>
		(<a href="http://ngircd.barton.de/pub/ngircd/ngircd-22~rc1.tar.xz.sig">Sig</a>),
		<a href="http://ngircd.barton.de/pub/ngircd/ngircd-22~rc1.tar.Z">tar.Z</a>
		(<a href="http://ngircd.barton.de/pub/ngircd/ngircd-22~rc1.tar.Z.sig">Sig</a>)
	</dd>
	<dd>

		Server: <em>ngircd.mirror.3rz.org</em>
		(<a href="http://ngircd.mirror.3rz.org/pub/ngircd/">http</a>):
		<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-22~rc1.tar.gz">ngircd-22~rc1.tar.gz</a>
		(<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-22~rc1.tar.gz.sig">Sig</a>),
		<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-22~rc1.tar.xz">tar.xz</a>
		(<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-22~rc1.tar.xz.sig">Sig</a>),
		<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-22~rc1.tar.Z">tar.Z</a>
		(<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-22~rc1.tar.Z.sig">Sig</a>)
	</dd>
</dl>
<dl>
	<dt>
		<strong>ngIRCd Release 21.1</strong> (2014-03-25):
	</dt>
	<dd>
		Server: <em>ngircd.barton.de</em>
		(<a href="http://ngircd.barton.de/pub/ngircd/">http</a>):
		<a href="http://ngircd.barton.de/pub/ngircd/ngircd-21.1.tar.gz">ngircd-21.1.tar.gz</a>
		(<a href="http://ngircd.barton.de/pub/ngircd/ngircd-21.1.tar.gz.sig">Sig</a>),
		<a href="http://ngircd.barton.de/pub/ngircd/ngircd-21.1.tar.xz">tar.xz</a>
		(<a href="http://ngircd.barton.de/pub/ngircd/ngircd-21.1.tar.xz.sig">Sig</a>),
		<a href="http://ngircd.barton.de/pub/ngircd/ngircd-21.1.tar.Z">tar.Z</a>
		(<a href="http://ngircd.barton.de/pub/ngircd/ngircd-21.1.tar.Z.sig">Sig</a>)
	</dd>
	<dd>

		Server: <em>ngircd.mirror.3rz.org</em>
		(<a href="http://ngircd.mirror.3rz.org/pub/ngircd/">http</a>):
		<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-21.1.tar.gz">ngircd-21.1.tar.gz</a>
		(<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-21.1.tar.gz.sig">Sig</a>),
		<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-21.1.tar.xz">tar.xz</a>
		(<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-21.1.tar.xz.sig">Sig</a>),
		<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-21.1.tar.Z">tar.Z</a>
		(<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-21.1.tar.Z.sig">Sig</a>)
	</dd>
</dl>
