<dl>
	<dt>
		<strong>ngIRCd Release 22.1</strong> (2015-04-06):
	</dt>
	<dd>
		Server: <em>ngircd.barton.de</em>
		(<a href="http://ngircd.barton.de/pub/ngircd/">http</a>):
		<a href="http://ngircd.barton.de/pub/ngircd/ngircd-22.1.tar.gz">ngircd-22.tar.gz</a>
		(<a href="http://ngircd.barton.de/pub/ngircd/ngircd-22.1.tar.gz.sig">Sig</a>),
		<a href="http://ngircd.barton.de/pub/ngircd/ngircd-22.1.tar.xz">tar.xz</a>
		(<a href="http://ngircd.barton.de/pub/ngircd/ngircd-22.1.tar.xz.sig">Sig</a>),
		<a href="http://ngircd.barton.de/pub/ngircd/ngircd-22.1.tar.Z">tar.Z</a>
		(<a href="http://ngircd.barton.de/pub/ngircd/ngircd-22.1.tar.Z.sig">Sig</a>)
	</dd>
	<dd>

		Server: <em>ngircd.mirror.3rz.org</em>
		(<a href="http://ngircd.mirror.3rz.org/pub/ngircd/">http</a>):
		<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-22.1.tar.gz">ngircd-22.tar.gz</a>
		(<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-22.1.tar.gz.sig">Sig</a>),
		<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-22.1.tar.xz">tar.xz</a>
		(<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-22.1.tar.xz.sig">Sig</a>),
		<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-22.1.tar.Z">tar.Z</a>
		(<a href="http://ngircd.mirror.3rz.org/pub/ngircd/ngircd-22.1.tar.Z.sig">Sig</a>)
	</dd>
</dl>
