ngIRCd 24-CHARCONV+DEBUG+IDENT+IPv6+IRCPLUS+PAM+SNIFFER+SSL+SYSLOG+TCPWRAP+ZLIB-x86_64/pc/linux-gnu
Copyright (c)2001-2017 Alexander Barton (<alex@barton.de>) and Contributors.
Homepage: <http://ngircd.barton.de/>

This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

  -d, --debug        log extra debug messages
  -f, --config <f>   use file <f> as configuration file
  -n, --nodaemon     don't fork and don't detach from controlling terminal
  -p, --passive      disable automatic connections to other servers
  -s, --sniffer      enable network sniffer and display all IRC traffic
  -t, --configtest   read, validate and display configuration; then exit
  -V, --version      output version information and exit
  -h, --help         display this help and exit

