<ul>
	<li>
		AIX
		(3.2.5 [IBM XL C Compiler])
	</li>
	<li>
		A/UX
		(3.x [Apple C Compiler, GNU C])
	</li>
	<li>
		<a href="http://www.freebsd.org/">FreeBSD</a>
		(4.5/i386 [GNU C])
	</li>
	<li>
		<a href="http://www.hp.com/">HP-UX</a>
		(10.20 [GNU C])
	</li>
	<li>
		<a href="http://www.hp.com/">HP-UX</a>
		(9.10/m68k [HP-UX cc]; 11.11/hppa [GNU C 4.2.3])
	</li>
	<li>
		IRIX
		(6.5 [SGI MIPSpro C 7.30])
	</li>
	<li>
		<a href="http://www.linux.org/">Linux</a>
		(2.2.x/i386, 2.4.x/i386+hppa, 2.6.x/i386+hppa [GNU C])
	</li>
	<li>
		<a href="http://www.apple.com/macosx/">Mac OS X</a>
		(10.x [GNU C 2.95.x, 3.x, 4.0.1])
	</li>
	<li>
		<a href="http://www.netbsd.org/">NetBSD</a>
		(1.5.2/i386, 1.5.3/m68k [GNU C])
	</li>
	<li>
		<a href="http://www.obenbsd.org/">OpenBSD</a>
		(3.4/i386 [GNU C])
	</li>
	<li>
		<a href="http://www.sun.com/">Solaris</a>
		(2.5.1, 2.6 [GNU C])
	</li>
	<li>
		Windows mit <a href="http://sources.redhat.com/cygwin/">Cygwin</a>
		(GNU C)
	</li>
</ul>

