<ul>
	<li>
		AIX
		(3.2.5 [IBM XL C Compiler])
	</li>
	<li>
		A/UX
		(3.x [Apple C Compiler, GNU C])
	</li>
	<li>
		<a href="https://www.freebsd.org">FreeBSD</a>
		(4.5 and newer on i386, x86_64 [GNU C])
	</li>
	<li>
		<a href="https://www.haiku-os.org/">Haiku</a>
		(on x86_64 [GNU C])
	</li>
	<li>
		<a href="https://www.hpe.com">HP-UX</a>
		(9.10, 10.20, 11.11 on hppa, m68k [HP-UX cc, GNU C])
	</li>
	<li>
		IRIX
		(6.5 [SGI MIPSpro C 7.30])
	</li>
	<li>
		<a href="https://www.linux.com">Linux</a>
		(2.x and newer; on hppa, i386, mipsel, powerpc, x86_64, ... [GNU C])
	</li>
	<li>
		<a href="https://www.apple.com/macos">macOS</a> (Darwin)
		(10.0 and newer on i386, powerpc, x86_64 [GNU C 2.95.x, 3.x, 4.x])
	</li>
	<li>
		<a href="https://www.netbsd.org/">NetBSD</a>
		(1.5.2 and newer on alpha, i386, m68k, sparc, x86_64, ... [GNU C])
	</li>
	<li>
		<a href="https://www.openbsd.org/">OpenBSD</a>
		(3.4 and newer on hppa, i386, powerpc, x86_64 [GNU C])
	</li>
	<li>
		<a href="https://www.sun.com/">Solaris</a>
		(2.5.1 and newer on i386, sparc [GNU C])
	</li>
	<li>
		Windows: <a href="https://www.cygwin.com">Cygwin</a> or
		<a href="https://learn.microsoft.com/windows/wsl">WSL</a>
		(GNU C)
	</li>
</ul>
