<ul>
	<li>
		AIX
		(3.2.5, IBM XL C Compiler)
	</li>
	<li>
		A/UX
		(3.x, original Apple C Compiler oder GNU C)
	</li>
	<li>
		<a href="http://www.freebsd.org/">FreeBSD</a>
		(4.5/i386, GNU C)
	</li>
	<li>
		<a href="http://www.hp.com/">HP-UX</a>
		(10.20, GNU C)
	</li>
	<li>
		<a href="http://www.hp.com/">HP-UX</a>
		(9.10/m68k, HP-UX cc)
	</li>
	<li>
		IRIX
		(6.5, SGI MIPSpro C 7.30)
	</li>
	<li>
		<a href="http://www.linux.org/">Linux</a>
		(2.2.x/i386, 2.4.x/i386 und 2.4.x/hppa, GNU C)
	</li>
	<li>
		<a href="http://www.apple.com/macosx/">Mac OS X</a>
		(10.x, GNU C 2.95.x/3.x/4.01)
	</li>
	<li>
		<a href="http://www.netbsd.org/">NetBSD</a>
		(1.5.2/i386 und 1.5.3/m68k, GNU C)
	</li>
	<li>
		<a href="http://www.obenbsd.org/">OpenBSD</a>
		(3.4/i386)
	</li>
	<li>
		<a href="http://www.sun.com/">Solaris</a>
		(2.5.1 und 2.6, GNU C)
	</li>
	<li>
		Windows mit <a href="http://sources.redhat.com/cygwin/">Cygwin</a>
		(GNU C)
	</li>
</ul>

